### ISSUE TITLE
Failed to load the atomize-d package

### ISSUE THREAD

**Issue by andreiamatuni** [Vild/atomize-d#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.4
**Thrown From**: [atomize-d](https://github.com/Vild/atomize-d) package, v0.1.0

### Stack Trace

Failed to load the atomize-d package

```
At Cannot find module 'semver'

Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/andrei/.atom/packages/atomize-d/lib/dub-config.coffee:3:10)
    at Object.<anonymous> (/Users/andrei/.atom/packages/atomize-d/lib/dub-config.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "language-d"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomize-d, v0.1.0
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.3
go-plus, v3.5.1
language-rust, v0.4.4
linter, v1.5.1
linter-rust, v0.2.9
minimap, v4.13.3
racer, v0.17.1
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by andreiamatuni** [comment]
realized i need to 'apm install' first, however now I get this error:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.4
**Thrown From**: [atomize-d](https://github.com/Vild/atomize-d) package, v0.1.0


### Stack Trace

Failed to activate the atomize-d package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:467:13)
    at new AtomizeDLinter (/Users/andrei/.atom/packages/atomize-d/lib/atomize-d-linter.coffee:16:30)
    at Object.module.exports.AtomizeD.activate (/Users/andrei/.atom/packages/atomize-d/lib/atomize-d.coffee:56:15)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "language-d"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomize-d, v0.1.0
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.3
go-plus, v3.5.1
language-rust, v0.4.4
linter, v1.5.1
linter-rust, v0.2.9
minimap, v4.13.3
racer, v0.17.1
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by Vild** [comment]
I will look up this tomorrow.

**Comment by Vild** [comment]
Oh, That problem is because there isn't an open project.
Currently most of the things are hacky implemented so they required that you have a project open.
Then you just need to reload atom via a "Window reload" which is Ctrl+Alt+R for me.

**Comment by andreiamatuni** [comment]
cool, now it works. windows reload was ctrl+alt+command+l for me

**Comment by Vild** [comment]
Sorry about that "hacky" way of fixing it.
I haven't had the time to implement it properly.
